# Generated by Django 5.0.7 on 2024-07-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("contract_version", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "pending"), (2, "active"), (3, "rejected"), (4, "paid")], default=1
                    ),
                ),
                ("outstanding", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="loans", to="customers.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
