version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: .
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dev-db-data:
  dev-static-data:
