FROM public.ecr.aws/f5k9u7m7/ecr_template_python_fargate
ARG ENVIRONMENT=default
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/
COPY ./src /usr/src/app/

COPY testing.sh /usr/local/bin/testing.sh
RUN chmod +x /usr/local/bin/testing.sh

COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY ./requirements /usr/src/app/requirements/

RUN pip install --upgrade pip && \
    pip install -r requirements/local.txt

RUN dos2unix /usr/local/bin/testing.sh

EXPOSE 8000
ENTRYPOINT ["testing.sh"]
