version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.testing
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app/
    depends_on:
      - db
    restart: on-failure

  db:
    image: public.ecr.aws/docker/library/postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  dev-db-data:
  dev-static-data:
