# Generated by Django 5.0.7 on 2024-07-25 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_otp_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_active",
        ),
    ]
