---
name: Checks and Linting code

on:
  push:
    branches:
      - master

jobs:
  pre-commit-validate:
    name: Validate with pre-commit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install pre-commit
      - name: pre-commit testing
        run: pre-commit run --all-files

  test-coverage:
    needs: [pre-commit-validate]
    name: Test coverage
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    strategy:
      max-parallel: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load environment variables
        run: echo "${{ secrets.ENVIRONMENT_VARIABLES }}" > .env
      - name: Run Tests with Coverage
        run: docker-compose -f docker-compose.testing.yml run django sh -c "coverage run manage.py test"
      - name: Validate Coverage
        run: |
          COVERAGE_PERCENTAGE=$(docker-compose -f docker-compose.testing.yml run --rm django sh -c "coverage report" | awk '/TOTAL/ {print $NF}' | tr -d '%')
          echo "This is the coverage ($COVERAGE_PERCENTAGE%)"
          if [[ $COVERAGE_PERCENTAGE -lt 80 ]]; then
            echo "Coverage percentage is below 80% ($COVERAGE_PERCENTAGE%)"
            exit 1
          fi
          echo "Generate coverage xml"
          docker-compose -f docker-compose.testing.yml run --rm django sh -c "coverage xml"
          docker-compose -f docker-compose.testing.yml run --rm django sh -c "coverage html"
          CONTAINER_ID=$(docker-compose -f docker-compose.testing.yml ps -a -q django)
          echo "Container ID: $CONTAINER_ID"
          docker ps
          docker ps -a
          docker cp $CONTAINER_ID:/src/coverage.xml .
          echo "show coverage.xml"
          ls -1 | grep 'coverage'
          echo "End coverage.xml"
      - name: Save coverage.xml as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-xml
          path: coverage.xml
